---
name: Build Tagged Image

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"

jobs:
  release-ghcr-on-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag from actions context
        id: gitref_tag
        run: echo ::set-output name=tag::${GITHUB_REF##*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push conatiner image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          push: true
          build-args: |
            APP_VERSION=${{ steps.gitref_tag.outputs.tag }}
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.gitref_tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
